services:
  mariadb:
    build:
      context: './mariadb'
      dockerfile: 'Dockerfile'
      args:
        MARIADB_VERSION: ${MARIADB_VERSION}
    environment:
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - '${DATA_PATH_HOST}:/var/lib/mysql'
    ports:
      - ${MARIADB_PORT}:3306

  phpmyadmin:
    build:
      context: './phpmyadmin'
      dockerfile: 'Dockerfile'
      args:
        PHP_MY_ADMIN_VERSION: ${PHP_MY_ADMIN_VERSION}
    environment:
      PMA_ARBITRARY: 0
      PMA_HOST: ${CONTAINER_PREFIX}-mariadb-1
      PMA_USER: root
      PMA_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - '${PMA_PORT}:80'
