#User defined
user:
  MariaDB_version:
    label:
      MariaDB version
    hint:
      Select a MariaDB version from the list above
    type:
      select
    values:
      - 10.7
      - 10.6
      - 10.5
    target:
      MARIADB_VERSION

#System defaults
system:
  #For collecting and storing DB in .env
  #db/user/password
  db_credentials:
    true
  #Generate public ports for the docker image
  ports:
    http:
      PMA_PORT
    others:
      - MYSQL_PORT


